dataset: "ego2hands"
model_2d_name: "CPM"
dataset_train_dir: "/home/alex/Documents/Data/Ego2Hands/train"
dataset_eval_dir: "/home/alex/Documents/Data/Ego2Hands/eval"
bg_all_dir: "/home/alex/Documents/Data/backgrounds"

num_2d_stages: 6
num_keypoints: 21

workers: 4
display_interval: 1000
save_interval: 2000
max_iter_2d: 100000
batch_size: 4
base_lr_2d: 0.0001
#-------------lr_policy--------------------#
policy_parameter_2d:
  gamma: 0.5
  step_size: 25000
