dataset: "ego2hands"
model_2d_name: "CPM"
experiment: "_BASELINE"
dataset_train_dir: "/home/alex/Documents/Data/Ego2Hands/train"
dataset_eval_dir: "/home/alex/Documents/Data/Ego2Hands/eval"
bg_all_dir: "/home/alex/Documents/Data/backgrounds"

num_2d_stages: 6
num_keypoints: 21

workers: 0
#display_interval: 250
#save_interval: 500
display_interval: 100
save_interval: 200

max_iter_2d: 40000000
batch_size: 20
base_lr_2d: 0.0003
#-------------lr_policy--------------------#
policy_parameter_2d:
  gamma: 0.7
  #step_size: 150
  patience: 10
  verbose: true